#!/bin/sh
set -euf

##
# Generate a random hex string with lower case
#
# Usage:
#
#     random-hex-lower [n]
#
# Options:
#
#   * `n` is the number of bytes; default is 16.
#      Note that this means the output string is twice as long.
#
# Example:
#
#     $ random-hex-lower
#     2a1af41f3b917b74018569722121ca27
#
# Alternate solution for Linux, using the tr command:
#
#     cat /dev/urandom | tr -cd '0-9a-f' | head -c 16; echo
#
# Alternate solution for BSD and Mac OS X, using the tr command:
#
#     cat /dev/urandom | env LC_CTYPE=C tr -cd '0-9a-f' | head -c 16; echo
#
# This implemenation uses the commands `hexdump` and `/dev/urandom` and `tr`.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or GPL or MIT or contact us for custom license
# Updated: 2021-10-14T15:42:48Z
##

len=${1-16}
hexdump -n "$len" -v -e '/1 "%02x"' -e "/$len \"\n\"" /dev/urandom
