#!/bin/sh
set -euf

##
# Generate a random hex fingerprint with upper case
#
# Usage:
#
#     random-hex-upper-fingerprint [n]
#
# Options:
#
#   * `n` is the number of bytes; default is 16.
#
# Example:
#
#     $ random-hex-upper-fingerprint
#     73:5C:6E:83:75:80:E4:04:7A:AE:AC:BA:EE:46:E6:43
#
# Note: 16 bytes is typical of fingerprints for SSH DSA, ECDSA, and RSA.
#
# This implementation uses `hexdump` and `/dev/urandom`.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: BSD or MIT or GPL or contact us for custom license
# Updated: 2021-10-14T15:42:48Z
##

len=${1-16}
hexdump -n $len -e "$len/1 \"%02X:\"" /dev/urandom | sed 's/:$//'
